services:
  fraueule-app:
    container_name: fraueule-app
    user: "${PUID}:${PGID}"
    image: wordpress:latest
    volumes:
      - ./theme:/var/www/html/wp-content/themes/fraueule
      - ./data:/var/www/html/wp-content
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - fraueule-db
    networks:
      - default
  fraueule-db:
    image: mariadb:10.11
    user: "${PUID}:${PGID}"
    container_name: fraueule-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --log_bin_trust_function_creators=true
    env_file:
      - .env      
    volumes:
        - ./db:/var/lib/mysql
    networks:
        - default